services:
  postgres:
    image: postgres:latest
    container_name: flaskcrud
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
    ports:
      - "5432:5432"
